const sampleEmails=[{sender:"Office of Examinations",subject:"Mid-semester examination schedule revised",preview:"The examination scheduled for 28 August has moved to 30 August.",date:"2026-08-26T10:15:00",content:"examination exam revised schedule",initials:"EX"},{sender:"Prof. Meera Iyer",subject:"DBMS assignment submission — due tomorrow",preview:"Submit Assignment 3 before 11:59 PM tomorrow.",date:"2026-08-26T09:20:00",content:"assignment submission due tomorrow deadline",initials:"MI"},{sender:"Academic Office",subject:"Attendance report for August",preview:"Your current attendance in Computer Networks is 71%.",date:"2026-08-25T16:40:00",content:"attendance is 71% academic warning",initials:"AO"},{sender:"Coding Club",subject:"Applications open: Inter-College Hackathon",preview:"Registrations close this Friday; teams of up to four are welcome.",date:"2026-08-25T12:10:00",content:"hackathon competition registration",initials:"CC"},{sender:"Career Development Cell",subject:"Summer internship opportunity at TechNova",preview:"Second-year students can apply for the software engineering internship.",date:"2026-08-24T15:30:00",content:"internship placement opportunity",initials:"CD"},{sender:"Photography Society",subject:"Join us for the monsoon photo walk",preview:"Meet us at the main gate this Sunday at 6:30 AM.",date:"2026-08-24T11:00:00",content:"club event photo walk",initials:"PS"}];
const rules={critical:["exam","examination","assignment","submission","deadline","fee due","academic warning","urgent","admit card","timetable revised"],moderate:["hackathon","internship","placement","scholarship","competition","workshop","coding contest"],low:["newsletter","survey","photo walk","club event","general announcement"]};
const state={filter:"all",query:"",sort:"priority",connected:false,csrfToken:""};let ranked=[];const priorityRank={critical:0,moderate:1,low:2};
function classify(email){const text=`${email.subject} ${email.preview} ${email.content}`.toLowerCase();const attendance=text.match(/attendance[^\d]{0,40}(\d{1,3}(?:\.\d+)?)\s*%/i);if(attendance&&Number(attendance[1])<75)return{priority:"critical",reason:`Attendance is ${attendance[1]}% — below 75%`};if(attendance)return{priority:"low",reason:`Attendance is ${attendance[1]}% — above 75%`};const critical=rules.critical.find(word=>text.includes(word));if(critical)return{priority:"critical",reason:`Detected: ${critical}`};const moderate=rules.moderate.find(word=>text.includes(word));if(moderate)return{priority:"moderate",reason:`Opportunity: ${moderate}`};const low=rules.low.find(word=>text.includes(word));return{priority:"low",reason:low?`Filtered: ${low}`:"No urgent action detected"}}
function relativeDate(value){const date=new Date(value),now=new Date();if(date.toDateString()===now.toDateString())return date.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});const days=Math.max(1,Math.round((now-date)/86400000));return days===1?"Yesterday":`${days}d ago`}
function escapeHtml(value=""){return value.replace(/[&<>"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]))}
function render(){let visible=ranked.filter(mail=>(state.filter==="all"||mail.priority===state.filter)&&`${mail.sender} ${mail.subject} ${mail.preview}`.toLowerCase().includes(state.query));visible.sort(state.sort==="newest"?(a,b)=>new Date(b.date)-new Date(a.date):(a,b)=>priorityRank[a.priority]-priorityRank[b.priority]||new Date(b.date)-new Date(a.date));document.querySelector("#mailList").innerHTML=visible.map(mail=>`<article class="mail ${mail.priority}" tabindex="0"><span class="sender-avatar">${escapeHtml(mail.initials||"?")}</span><div class="sender"><strong>${escapeHtml(mail.sender)}</strong><small>${mail.priority==="critical"?"Action may be required":mail.priority==="moderate"?"Opportunity":"General update"}</small></div><div class="message"><strong>${escapeHtml(mail.subject)}</strong><p>${escapeHtml(mail.preview)}</p><small class="reason">${escapeHtml(mail.reason)}</small></div><time class="time">${relativeDate(mail.date)}</time></article>`).join("");document.querySelector("#emptyState").hidden=visible.length>0}
function updateCounts(){const counts={critical:0,moderate:0,low:0};ranked.forEach(e=>counts[e.priority]++);["critical","moderate","low"].forEach(key=>{document.querySelector(`#${key}Count`).textContent=counts[key];document.querySelector(`#${key}NavCount`).textContent=counts[key]});document.querySelector("#allCount").textContent=ranked.length;document.querySelector("#urgentSummary").textContent=`${counts.critical} messages may need action`}
function loadEmails(emails){ranked=emails.map(email=>email.priority&&email.reason?email:{...email,...classify(email)});updateCounts();render()}
function setFilter(filter){state.filter=filter;document.querySelectorAll("[data-filter]").forEach(button=>button.classList.toggle("active",button.dataset.filter===filter));render()}
function setConnectButton(connected,configured=true){state.connected=connected;const button=document.querySelector("#connectButton");button.innerHTML=connected?"✓ Gmail connected":`<span class="google-g">G</span> ${configured?"Connect Gmail":"Set up Gmail"}`;button.title=connected?"Click to disconnect Gmail":"Connect using Google OAuth"}
async function checkConnection(){try{const response=await fetch("/api/auth/status");if(!response.ok)throw new Error();const status=await response.json();state.csrfToken=status.csrfToken;setConnectButton(status.connected,status.configured);if(status.connected){const mailResponse=await fetch("/api/emails");if(!mailResponse.ok)throw new Error();const data=await mailResponse.json();loadEmails(data.emails)}else loadEmails(sampleEmails)}catch{setConnectButton(false,false);loadEmails(sampleEmails)}}
async function connectOrDisconnect(){if(state.connected){if(confirm("Disconnect Gmail, revoke Campus Inbox access, and end this session?")){const response=await fetch("/api/auth/logout",{method:"POST",headers:{"x-csrf-token":state.csrfToken}});const result=await response.json();if(!response.ok){alert(result.error||"Could not disconnect. Refresh and try again.");return}setConnectButton(false,true);state.csrfToken="";loadEmails(sampleEmails);if(!result.revoked)alert(result.warning)}}else window.location.href="/auth/google"}
async function deleteMyData(){if(!state.connected){alert("Connect Gmail before deleting account data.");return}if(!confirm("Permanently delete your cached Campus Inbox data, revoke Gmail access, and end this session? Your original Gmail emails will NOT be deleted."))return;const response=await fetch("/api/account/data",{method:"DELETE",headers:{"x-csrf-token":state.csrfToken}});const result=await response.json();if(!response.ok){alert(result.error||"Could not delete your data. Refresh and try again.");return}document.querySelector("#rulesDialog").close();setConnectButton(false,true);state.csrfToken="";loadEmails(sampleEmails);alert(`Deleted ${result.deletedRecords} cached message records. Your Gmail messages were not deleted.${result.warning?`\n\n${result.warning}`:""}`)}
document.querySelectorAll("[data-filter]").forEach(button=>button.addEventListener("click",()=>setFilter(button.dataset.filter)));document.querySelector("#searchInput").addEventListener("input",e=>{state.query=e.target.value.toLowerCase().trim();render()});document.querySelector("#sortSelect").addEventListener("change",e=>{state.sort=e.target.value;render()});document.querySelector("#settingsButton").addEventListener("click",()=>document.querySelector("#rulesDialog").showModal());document.querySelector("#connectButton").addEventListener("click",connectOrDisconnect);document.querySelector("#deleteDataButton").addEventListener("click",deleteMyData);checkConnection();
